# Generated by Django 3.0.6 on 2020-05-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TDesf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona responsable')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='desfs', verbose_name='Imagen o foto')),
                ('tdesf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TDesf.Tdesf', verbose_name='Tipo de desfibrilador')),
            ],
            options={
                'verbose_name': 'desf',
                'verbose_name_plural': 'desfs',
            },
        ),
    ]
