# Generated by Django 3.0.6 on 2020-05-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Desf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de transmisión')),
                ('hora', models.TimeField(verbose_name='Hora de transmisión')),
                ('imagen', models.CharField(max_length=100, verbose_name='Texto transmitido')),
                ('desf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desf.Desf', verbose_name='Desfibrilador')),
            ],
            options={
                'verbose_name': 'tran',
                'verbose_name_plural': 'trans',
            },
        ),
    ]
